{{if and .Values.ingress.enabled .Values.ingress.cloudflareToken}}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  labels:
    {{- include "trilium-oauth2-chart.labels" . | nindent 4 }}
type: Opaque
data:
  api-token: {{.Values.ingress.cloudflareToken | b64enc }}
{{- end }}